version: '3.8'
services:
  db:
    image: postgres:17
    container_name: terrea_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env-non-dev
    ports:
      - "5433:5432"
  
  redis:
    image: redis:7
    container_name: terrea_redis
    ports:
      - "6379:6379"
  
  terrea:
    image: terrea_image
    container_name: terrea_app
    build:
      context: .
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    command: ["/terrea/docker/app.sh"]
    ports:
      - 8000:8000
      
volumes:
  postgresdata: