version: '3.8'
services:
  terrea:
    image: terrea_image
    container_name: terrea_app
    build:
      context: .
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    command: sh -c "alembic upgrade head && gunicorn src.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 8000:8000

  db:
    image: postgres:17
    container_name: terrea_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env-non-dev
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    container_name: terrea_redis
    ports:
      - "6379:6379"

  celery:
    image: celery_image
    container_name: celery_app
    build:
      context: .
    depends_on:
      - redis
    env_file:
      - .env-non-dev
    command: sh -c "celery -A src.tasks.celery:app_celery worker --loglevel=INFO --pool=solo"

  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheusdata:/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:9.4.7
    container_name: grafana
    volumes:
      - grafanadata:/var/lib/grafana
    restart: unless-stopped
    ports:
      - 3000:3000

volumes:
  postgresdata:
  prometheusdata:
  grafanadata: