"""Add performer_id in Task model

Revision ID: 6061c5eb5eea
Revises: 561367643ffe
Create Date: 2024-11-30 12:18:00.950162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6061c5eb5eea'
down_revision: Union[str, None] = '561367643ffe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('performer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'task', 'user', ['performer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'performer_id')
    # ### end Alembic commands ###
