"""Make realtionship

Revision ID: 561367643ffe
Revises: c4bb5d352805
Create Date: 2024-11-26 09:15:57.362867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '561367643ffe'
down_revision: Union[str, None] = 'c4bb5d352805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'task', 'user', ['customer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'customer_id')
    # ### end Alembic commands ###
